# this code is from the RFC
crc_table = (0...256).map do |n|
  (0...8).reduce(n) do |c|
    if c & 1 != 0
      0xedb8_8320 ^ (c >> 1)
    else
      c >> 1
    end
  end
end

per_line = 6

puts "// autogenerated by make_crc_table.rb"
print "static crc_table: [u32, ..256] = ["
(0...256).each do |i|
  if i % per_line == 0
    print "\n   "
  end
  print "0x#{crc_table[i].to_s(16).rjust(8, "0")}, "
end
puts "\n];"
